What does the following print out?

function f() {
    throw 500;
}

function g() {
    try{
        f();
    } catch(err) {
        console.log(err);
    }
}

// nothing, depends which functions are called